# Generated by Django 5.1 on 2024-08-25 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDeEnvioNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data_envio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='pendente', max_length=10)),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificado.certificado')),
                ('data_envio_notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificacao.datadeenvionotificacao')),
            ],
        ),
    ]
