# Generated by Django 4.2.15 on 2024-08-16 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0004_remove_telefonecliente_enviar_mensagem_cliente_email'),
        ('certificado', '0003_alter_certificado_numero_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('mensagem', models.TextField()),
                ('periodo', models.IntegerField(choices=[(30, '30 dias antes'), (15, '15 dias antes'), (5, '5 dias antes')])),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificado.certificado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
