# Generated by Django 4.2.15 on 2024-08-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
