# Generated by Django 4.2.15 on 2024-08-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0002_remove_notificacao_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='cliente',
        ),
    ]
