# Generated by Django 4.2.15 on 2024-08-16 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0003_remove_notificacao_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='data_envio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
