# Generated by Django 4.2.15 on 2024-08-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datadeenvionotificacao',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={},
        ),
        migrations.RemoveField(
            model_name='datadeenvionotificacao',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='datadeenvionotificacao',
            name='status',
        ),
        migrations.AlterField(
            model_name='datadeenvionotificacao',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='canal',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='pendente', max_length=10),
        ),
    ]
