# Generated by Django 5.0.1 on 2024-08-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(default='admin@example.com', max_length=254)),
                ('notification_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
