# Generated by Django 4.2.15 on 2024-08-12 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrumento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificado', models.CharField(max_length=255, unique=True)),
                ('data_validade', models.DateField()),
                ('instrumento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='instrumento.instrumento')),
            ],
        ),
    ]
