# Generated by Django 4.2.15 on 2024-08-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0001_initial'),
    ]

    operations = [
        
    ]
