# Generated by Django 4.2.15 on 2024-08-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0002_certificado_data_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='numero_certificado',
            field=models.CharField(max_length=255),
        ),
    ]
