# Generated by Django 4.2.15 on 2024-08-12 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_remove_cliente_telefone_telefonecliente_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='telefonecliente',
            options={'verbose_name': 'Telefone do Cliente', 'verbose_name_plural': 'Telefones dos Clientes'},
        ),
        migrations.AddField(
            model_name='telefonecliente',
            name='enviar_mensagem',
            field=models.BooleanField(default=False, verbose_name='Enviar Mensagem'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='telefonecliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='telefonecliente',
            name='numero',
            field=models.CharField(max_length=14, verbose_name='Número de Telefone'),
        ),
    ]
