# Generated by Django 4.2.15 on 2024-08-12 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=255, unique=True)),
                ('data_instalacao', models.DateField()),
                ('tipo_instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='instrumento.tipoinstrumento')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrumentos', to='veiculo.veiculo')),
            ],
        ),
    ]
