# Generated by Django 4.2.15 on 2024-08-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0002_remove_instrumento_data_instalacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinstrumento',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
