# Generated by Django 4.2.15 on 2024-08-14 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0003_alter_tipoinstrumento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinstrumento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
